# Generated by Django 4.1.2 on 2022-10-31 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'ordering': ['id'], 'verbose_name': 'job category', 'verbose_name_plural': 'job categories'},
        ),
    ]
