# Generated by Django 4.1.2 on 2022-10-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_secrets_alter_business_config_and_more'),
        ('job_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='business',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(data_name)s', to='business.business'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
