# Generated by Django 4.1.2 on 2022-10-31 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['id'], 'verbose_name': 'technology', 'verbose_name_plural': 'technologies'},
        ),
    ]
