# Generated by Django 4.0.7 on 2022-08-27 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0001_initial'),
        ('location', '0001_initial'),
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('built_in_url', models.URLField(default=None, max_length=256, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('year_founded', models.IntegerField(default=None, null=True)),
                ('employees', models.IntegerField(default=None, null=True)),
                ('tagline', models.TextField(default=None, null=True)),
                ('company_url', models.URLField(default=None, max_length=256, null=True)),
                ('industries', models.ManyToManyField(related_name='%(class)s_relations', to='industry.industry')),
                ('location', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_relation', to='location.location')),
                ('technologies', models.ManyToManyField(related_name='%(class)s_relations', to='technology.technology')),
            ],
            options={
                'verbose_name': 'business',
                'verbose_name_plural': 'businesses',
                'db_table': 'built_in_business',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
