# Generated by Django 4.0.7 on 2022-08-28 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['id'], 'verbose_name': 'business', 'verbose_name_plural': 'businesses'},
        ),
    ]
