# Generated by Django 4.0.7 on 2022-08-28 04:23

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='config',
            field=systems.models.fields.EncryptedDataField(default={}, editable=False),
        ),
        migrations.AddField(
            model_name='business',
            name='provider_type',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='variables',
            field=systems.models.fields.EncryptedDataField(default={}, editable=False),
        ),
    ]
